# Generated by Django 3.2.8 on 2021-11-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_customerlenspackage_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlenspackage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.customer'),
        ),
        migrations.AlterField(
            model_name='customerlenspackage',
            name='lens_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.lenspackage'),
        ),
        migrations.AlterField(
            model_name='lenspackage',
            name='lens_add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.lensaddons'),
        ),
        migrations.AlterField(
            model_name='lenspackage',
            name='lens_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.lensmaterial'),
        ),
        migrations.AlterField(
            model_name='lenspackage',
            name='lens_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.lenstype'),
        ),
    ]
