# Generated by Django 3.2.8 on 2022-02-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_magnificationlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('notes', models.CharField(default='', max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lens_design_item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.lensdesignitem')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
