# Generated by Django 3.2.8 on 2022-02-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_normform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normform',
            options={'verbose_name': 'Norm Form', 'verbose_name_plural': 'Norm Forms'},
        ),
        migrations.RemoveField(
            model_name='normform',
            name='lens_design_item',
        ),
    ]
