# Generated by Django 3.2.8 on 2022-02-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_auto_20220224_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='normform',
            name='appearance',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
