# Generated by Django 3.2.8 on 2022-02-25 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_normform_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mrn', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.RemoveField(
            model_name='lensdesignitem',
            name='lens_add_on',
        ),
        migrations.RemoveField(
            model_name='lensdesignitem',
            name='lens_design',
        ),
        migrations.RemoveField(
            model_name='lensdesignitem',
            name='lens_material',
        ),
        migrations.RemoveField(
            model_name='lensdesignitem',
            name='lens_type',
        ),
        migrations.DeleteModel(
            name='MagnificationLevel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lens_design_item',
        ),
        migrations.DeleteModel(
            name='LensAddOns',
        ),
        migrations.DeleteModel(
            name='LensDesign',
        ),
        migrations.DeleteModel(
            name='LensDesignItem',
        ),
        migrations.DeleteModel(
            name='LensMaterial',
        ),
        migrations.DeleteModel(
            name='LensType',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='normform',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.patient'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
