# Generated by Django 3.2.8 on 2022-02-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_alter_patient_mrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
