# Generated by Django 3.2.8 on 2022-02-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_alter_patient_mrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normform',
            name='affect_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='agg_behavior_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='appetite_change_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='attention_concentration_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='attitude_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='chief_complaints_problems_history',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='communication_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='current_medication',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='diagnostic_impression',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='discussion_treatment',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='facility',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.facility'),
        ),
        migrations.AlterField(
            model_name='normform',
            name='gen_appearance_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='harmfulness_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='inappropriate_behavior_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='insight_judgement_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='level_of_consciousness_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='mood_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='orientation_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.patient'),
        ),
        migrations.AlterField(
            model_name='normform',
            name='perceptual_disturbances_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='sleep_disturbance_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='speech_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='thought_content_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='thought_process_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='treat_and_compliance_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='normform',
            name='verbal_abilities_notes',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
    ]
