# Generated by Django 3.2.8 on 2022-03-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_alter_normform_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normform',
            old_name='appetite_change_tobacco_screen',
            new_name='tobacco_screen',
        ),
    ]
