# Generated by Django 3.2.8 on 2022-03-07 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_normform_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normform',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
