# Generated by Django 3.2.8 on 2022-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0042_alter_normform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='normform',
            name='treat_and_compliance_wandering',
            field=models.BooleanField(default=False),
        ),
    ]
