# Generated by Django 3.2.8 on 2022-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0043_normform_treat_and_compliance_wandering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normform',
            old_name='appetite_change',
            new_name='appetite_change_no',
        ),
        migrations.AddField(
            model_name='normform',
            name='appetite_change_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normform',
            name='sleep_disturbance_hypnagogic_hypnopompic_hallucinations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normform',
            name='sleep_disturbance_nightmares',
            field=models.BooleanField(default=False),
        ),
    ]
