# Generated by Django 3.2.8 on 2022-04-01 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0044_auto_20220326_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('full_text', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subjective Option',
                'verbose_name_plural': 'Subjective Options',
            },
        ),
        migrations.CreateModel(
            name='DiscussionTreatmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('full_text', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion and Treatment Option',
                'verbose_name_plural': 'Discussion and Treatment Options',
            },
        ),
        migrations.AddField(
            model_name='normform',
            name='discussion_treatment_options',
            field=models.ManyToManyField(blank=True, to='form.DiscussionTreatmentOption'),
        ),
        migrations.AddField(
            model_name='normform',
            name='subjective_options',
            field=models.ManyToManyField(blank=True, to='form.SubjectiveOption'),
        ),
    ]
