# Generated by Django 3.2.8 on 2022-04-15 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0046_subjectiveboilerplateoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=1000, null=True)),
                ('diagnosis_code', models.CharField(max_length=1000, null=True)),
                ('full_code', models.CharField(max_length=1000, null=True)),
                ('abbreviated_description', models.CharField(max_length=1000, null=True)),
                ('full_description', models.CharField(max_length=10000, null=True)),
                ('category_title', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ICD-10 Code',
                'verbose_name_plural': 'ICD-10 Codes',
            },
        ),
    ]
