# Generated by Django 3.2.8 on 2022-04-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0048_auto_20220415_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='normform',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
