# Generated by Django 3.2.8 on 2022-04-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0049_normform_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normform',
            name='name',
        ),
    ]
