# Generated by Django 3.2.8 on 2022-04-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0050_remove_normform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normform',
            name='sleep_disturbance_describe',
        ),
    ]
