# Generated by Django 3.2.8 on 2022-05-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0053_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
