# Generated by Django 3.2.8 on 2022-05-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0054_patient_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='normform',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
