# Generated by Django 3.2.8 on 2022-08-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0058_auto_20220822_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='facility',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.facility'),
        ),
    ]
