# Generated by Django 3.2.8 on 2022-08-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0060_auto_20220822_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
