# Generated by Django 3.2.8 on 2022-08-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0061_alter_physician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
