# Generated by Django 3.2.8 on 2022-08-30 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0063_auto_20220822_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.facility'),
        ),
    ]
