# Generated by Django 3.2.8 on 2023-11-22 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0065_auto_20231121_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='sr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='sr_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
