# Generated by Django 3.2.8 on 2023-11-22 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0066_auto_20231122_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='sr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='sr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
